### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by ereday** [bwilder0/aaai_melding_code#3]
Hi @bwilder0,

First of all thanks for such a great work!

There is already another issue about this (raised by @289371298 on October,11), there are  a couple of important files missing in the repository. As you can see at lines 51-52 of matching.py, we need cora_graphs_bipartite.pt and cora_features_bipartite.pt files to be able to use the code. Unfortunately, they are neither available in the repository nor in the data_decisions_bencmark.zip file that you mention in the README. Could you please also share those necessary files so that we can actually use the code? 

Thanks!

**Comment by bwilder0** [comment]
Hi @ereday! Thank you for reminding me of this issue, and apologies for letting this slip through the cracks before. I have added links to directly download those files to the project readme. Please let me know if there are any remaining problems.

**Comment by ereday** [comment]
@bwilder0  Great, thanks!
